library(readxl)
library(here)
library(dplyr)
library(readr)
library(tidyr)
library(stringr)
try1 <- read_csv("Test Code/Merge Test/Canvas Merge/Survey Merge/Aut 2016 CHEM 142 Student Surveys 2 Survey Student Analysis Report.csv")
try2 <-  print(try1,quote = FALSE)
write.csv(noquote(try2),"try3.csv", row.names=FALSE)